physics: { tick: 16, gravity: [ 0.34, -3 ], drag: 0.8 }
ease:    { stress: 0.01, eye: 0.25, target: 0.5,  drag: 0.2 }

worm:
  size: 1
  proportions: {fat: 250, eyes: 4, body: 8, mouth: 4, tongue: 2, } # Multiply by size
  color: { eyes: "red", body: "black", mouth: "black", tongue: "crimson" }
  behavior:
      blink: { delay: 6000, duration: 220 }
      peak: 60
  options: { smooth: true, rainbow: true }
      